export const FARMLANDS = [
  {
    id: "sundance-corn-estate",
    name: "Sundance Corn Estate",
    location: "Nebraska, USA",
    image: "/farm.jpg",
    yield: "12.4%",
    risk: "Low",
    minInvestment: "$500",
    tech: ["AI Irrigation", "Autonomous Tractors"],
    cropType: "Corn",
    rotationDays: 120,
    trending: true,
    fundedPct: 82,
    totalGoal: "$2.3M",
  },
  {
    id: "blue-ridge-orchard",
    name: "Blue Ridge Apple Orchard",
    location: "Virginia, USA",
    image: "/farm.jpg", 
    yield: "14.1%",
    risk: "Medium",
    minInvestment: "$1,000",
    tech: ["Drone Scouting", "Soil Sensors"],
    cropType: "Apples",
    rotationDays: 365,
    trending: true,
    fundedPct: 65,
    totalGoal: "$1.5M",
  },
  {
    id: "golden-wheat-coop",
    name: "Golden Wheat Co-operative",
    location: "Kansas, USA",
    image: "/farm.jpg",
    yield: "10.5%",
    risk: "Low",
    minInvestment: "$250",
    tech: ["Satellite Imaging", "Predictive Weather"],
    cropType: "Wheat",
    rotationDays: 90,
    trending: false,
    fundedPct: 95,
    totalGoal: "$4.0M",
  },
  {
    id: "emerald-vineyards",
    name: "Emerald Vineyards",
    location: "California, USA",
    image: "/farm.jpg",
    yield: "16.8%",
    risk: "High",
    minInvestment: "$5,000",
    tech: ["Smart Drip", "Robotic Harvesting"],
    cropType: "Grapes",
    rotationDays: 180,
    trending: true,
    fundedPct: 40,
    totalGoal: "$8.5M",
  },
  {
    id: "dakota-soy-fields",
    name: "Dakota Soy Fields",
    location: "South Dakota, USA",
    image: "/farm.jpg",
    yield: "11.2%",
    risk: "Medium",
    minInvestment: "$500",
    tech: ["Variable Rate Tech", "AI Irrigation"],
    cropType: "Soybeans",
    rotationDays: 110,
    trending: false,
    fundedPct: 15,
    totalGoal: "$3.2M",
  },
  {
    id: "cascade-hops-farm",
    name: "Cascade Hops Farm",
    location: "Washington, USA",
    image: "/farm.jpg",
    yield: "15.0%",
    risk: "High",
    minInvestment: "$2,500",
    tech: ["Vertical Trellis", "Smart Sensors"],
    cropType: "Hops",
    rotationDays: 150,
    trending: true,
    fundedPct: 55,
    totalGoal: "$1.8M",
  },
  {
    id: "delta-rice-co",
    name: "Delta Rice Co.",
    location: "Arkansas, USA",
    image: "/farm.jpg",
    yield: "9.8%",
    risk: "Low",
    minInvestment: "$1,000",
    tech: ["Water Management AI", "Drone Scouting"],
    cropType: "Rice",
    rotationDays: 140,
    trending: false,
    fundedPct: 20,
    totalGoal: "$5.0M",
  },
  {
    id: "peach-grove-ga",
    name: "Peach Grove",
    location: "Georgia, USA",
    image: "/farm.jpg",
    yield: "13.5%",
    risk: "Medium",
    minInvestment: "$750",
    tech: ["Climate Control", "Automated Sorting"],
    cropType: "Peaches",
    rotationDays: 120,
    trending: true,
    fundedPct: 88,
    totalGoal: "$2.1M",
  },
  {
    id: "montana-barley-fields",
    name: "Montana Barley Fields",
    location: "Montana, USA",
    image: "/farm.jpg",
    yield: "10.0%",
    risk: "Low",
    minInvestment: "$500",
    tech: ["Satellite Imaging", "Soil Sensors"],
    cropType: "Barley",
    rotationDays: 100,
    trending: false,
    fundedPct: 42,
    totalGoal: "$6.2M",
  },
  {
    id: "florida-citrus-orchard",
    name: "Sunshine Citrus Orchard",
    location: "Florida, USA",
    image: "/farm.jpg",
    yield: "14.5%",
    risk: "Medium",
    minInvestment: "$1,500",
    tech: ["Disease Prediction AI", "Smart Drip"],
    cropType: "Oranges",
    rotationDays: 365,
    trending: true,
    fundedPct: 70,
    totalGoal: "$3.5M",
  },
  {
    id: "pampas-soy-fields",
    name: "Pampas Soy Fields",
    location: "Argentina",
    image: "/farm.jpg",
    yield: "14.2%",
    risk: "Medium",
    minInvestment: "$2,000",
    tech: ["Satellite Imaging", "Predictive Weather"],
    cropType: "Soybeans",
    rotationDays: 130,
    trending: true,
    fundedPct: 60,
    totalGoal: "$5.5M",
  },
  {
    id: "bordeaux-vineyards",
    name: "Château Bordeaux",
    location: "France",
    image: "/farm.jpg",
    yield: "9.5%",
    risk: "Low",
    minInvestment: "$10,000",
    tech: ["Smart Drip", "Soil Sensors"],
    cropType: "Grapes",
    rotationDays: 365,
    trending: false,
    fundedPct: 85,
    totalGoal: "$12.0M",
  },
  {
    id: "mekong-delta-rice",
    name: "Mekong Delta Rice",
    location: "Vietnam",
    image: "/farm.jpg",
    yield: "11.8%",
    risk: "Medium",
    minInvestment: "$500",
    tech: ["Drone Scouting", "Water Management AI"],
    cropType: "Rice",
    rotationDays: 110,
    trending: true,
    fundedPct: 92,
    totalGoal: "$1.2M",
  },
  {
    id: "rift-valley-coffee",
    name: "Rift Valley Coffee",
    location: "Kenya",
    image: "/farm.jpg",
    yield: "18.5%",
    risk: "High",
    minInvestment: "$1,500",
    tech: ["Climate Control", "Disease Prediction AI"],
    cropType: "Coffee",
    rotationDays: 300,
    trending: true,
    fundedPct: 45,
    totalGoal: "$2.8M",
  },
  {
    id: "punjab-wheat-coop",
    name: "Punjab Wheat Co-op",
    location: "India",
    image: "/farm.jpg",
    yield: "10.2%",
    risk: "Low",
    minInvestment: "$250",
    tech: ["AI Irrigation", "Predictive Weather"],
    cropType: "Wheat",
    rotationDays: 120,
    trending: false,
    fundedPct: 98,
    totalGoal: "$4.5M",
  },
  {
    id: "cerrado-coffee-estate",
    name: "Cerrado Coffee Estate",
    location: "Brazil",
    image: "/farm.jpg",
    yield: "15.4%",
    risk: "Medium",
    minInvestment: "$3,000",
    tech: ["Automated Sorting", "Soil Sensors"],
    cropType: "Coffee",
    rotationDays: 280,
    trending: true,
    fundedPct: 30,
    totalGoal: "$8.0M",
  },
  {
    id: "andalusia-olive-groves",
    name: "Andalusia Olive Groves",
    location: "Spain",
    image: "/farm.jpg",
    yield: "12.0%",
    risk: "Low",
    minInvestment: "$5,000",
    tech: ["Smart Sensors", "Drone Scouting"],
    cropType: "Olives",
    rotationDays: 365,
    trending: false,
    fundedPct: 77,
    totalGoal: "$6.0M",
  },
  {
    id: "queensland-sugarcane",
    name: "Queensland Sugarcane",
    location: "Australia",
    image: "/farm.jpg",
    yield: "13.8%",
    risk: "High",
    minInvestment: "$1,000",
    tech: ["Robotic Harvesting", "Water Management AI"],
    cropType: "Sugarcane",
    rotationDays: 365,
    trending: true,
    fundedPct: 50,
    totalGoal: "$3.8M",
  }
];
